// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFUEqqDVulMaPc3nzs-qvgE22zdZGNM0E',
    appId: '1:742060755704:web:a3470b68fff8d255a5c90d',
    messagingSenderId: '742060755704',
    projectId: 'projectmaster-6cc96',
    authDomain: 'projectmaster-6cc96.firebaseapp.com',
    storageBucket: 'projectmaster-6cc96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiPR4YSd0jKMTVltZne3jIjEqSyqk4Crw',
    appId: '1:742060755704:android:ab2cb3ad70f7e857a5c90d',
    messagingSenderId: '742060755704',
    projectId: 'projectmaster-6cc96',
    storageBucket: 'projectmaster-6cc96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQNeVmOOpG9sdMffwvvGdt8OEVd66dlto',
    appId: '1:742060755704:ios:f04f69a5e30b7a2aa5c90d',
    messagingSenderId: '742060755704',
    projectId: 'projectmaster-6cc96',
    storageBucket: 'projectmaster-6cc96.firebasestorage.app',
    iosBundleId: 'com.example.team',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQNeVmOOpG9sdMffwvvGdt8OEVd66dlto',
    appId: '1:742060755704:ios:f04f69a5e30b7a2aa5c90d',
    messagingSenderId: '742060755704',
    projectId: 'projectmaster-6cc96',
    storageBucket: 'projectmaster-6cc96.firebasestorage.app',
    iosBundleId: 'com.example.team',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFUEqqDVulMaPc3nzs-qvgE22zdZGNM0E',
    appId: '1:742060755704:web:f4929933b40974b5a5c90d',
    messagingSenderId: '742060755704',
    projectId: 'projectmaster-6cc96',
    authDomain: 'projectmaster-6cc96.firebaseapp.com',
    storageBucket: 'projectmaster-6cc96.firebasestorage.app',
  );
}
